id: PF4FF6FF5
initial_creation_type: input
source_metadata:
  title: Swift Rebirth Prayers
  language: zh
  description: 'A selection of prayers for the swift rebirth (myur byon gsol ’debs)
    of prominent individuals (arranged alphabetically by subject):'
  volume:
    9b8d7099304c48e3af77d2bb11325009:
      title: 'The Swift Fulfilment of Wishes: A Prayer for the Swift Return of the
        Supreme Tulku of the Fifth Drubwang Dzogchen Rinpoche'
      parent: Fifth Dzogchen Rinpoche
    263b853ff474462eaeecd642c26f0705:
      title: Prayer for Swift Rebirth of the Fourth Dodrupchen Rinpoche
      parent: Fourth Dodrupchen Rinpoche
    df77260c469f411a988113eeb4dd1f1f:
      title: Prayer for Swift Rebirth of the Fourth Dodrupchen Rinpoche, Tupten Trinlé
        Palzangpo
      parent: Fourth Dodrupchen Rinpoche
    59c655de41744a6fa4b080296c6368be:
      title: Prayer for the Swift Rebirth of the Fourth Dodrupchen Rinpoche
      parent: Fourth Dodrupchen Rinpoche
    a2c8cdfd39d24131bcfef36d43596a50:
      title: A Prayer for the Swift Return of the Fourth Kyabje Dodrupchen Rinpoche
      parent: Fourth Dodrupchen Rinpoche
    d9a9ba8ac79b4a16847d8fdad54941a5:
      title: 'The Moonlight of Auspiciousness: A Yearning Prayer to the Noble and
        Glorious Guru Combined with an Aspiration for His Swift Return'
      parent: Gyurme Tsewang Gyatso
    5e306a03b13a49f9b88e37fd7da6d372:
      title: Prayer to Kongtrul Yönten Gyatso
      parent: Jamgön Kongtrul Lodrö Thaye
    b5283cba489b4726b1756235b4c1c126:
      title: Prayer for the Swift Rebirth of Jamyang Khyenrab Tayé
      parent: Jamyang Khyenrab Tayé
    79255bd92ae84a7c8189da327af9f4ab:
      title: Lamenting Prayer to Jamyang Chökyi Lodrö
      parent: Jamyang Khyentse Chökyi Lodrö
    c614361408124c69aedeacec1e73b021:
      title: 'Wondrous Light of the Moon: A Prayer for the Swift Appearance of the
        Supreme Tulku of Vajradhara'
      parent: Jamyang Loter Wangpo
    bfcd1746a1394955ac56c46bbedb7ec9:
      title: 'The Swift Fulfilment of Wishes: Prayer for the Swift Appearance of the
        Supreme Tulku of the Mañjughoṣa Guru'
      parent: Katok Situ Chökyi Gyatso
    1044d100e8f64189938a301c51d9eaee:
      title: 'Cymbals to Invoke a Compassionate Response: A Prayer for Swift Rebirth
        of Khandro Tsering Chödrön'
      parent: Khandro Tsering Chödrön
    c8b452f8936f40e599c52f6523bffe70:
      title: 'The Swift Infusion of Blessings: A Lament and Prayer to Invoke the Wisdom
        Mind of Khenchen Vāgindra on the Occasion of His Passing into the Great Peace
        of the Dharmadhātu'
      parent: Ngawang Samten Lodrö
    bb27ca2a00144c978b9f7a0dd93ccedf:
      title: A Prayer for the Swift Rebirth of Tenpai Nyima Rinpoche
      parent: Tenpai Nyima Rinpoche
    fc76662e879e4769a7be8cb69bb1c5bf:
      title: 'The Tambura of Devotion: A Prayer for the Swift Appearance of the Supreme
        Tulku of the All-Seeing Conqueror and Cardinal Guardian of the Land of Snows'
      parent: Thirteenth Dalai Lama
    8b8b561f062d449ab1d6312d6af07fab:
      title: Prayer for the Swift Rebirth of Kyabjé Trulshik Rinpoche
      parent: Trulshik Rinpoche
created_at: '2022-03-01T05:59:59.960479'
last_modified_at: '2022-03-01T05:59:59.960482'
